_id: spc_eb8f4dd258224cc0a2d59fe526643078
type: ApiSpec
parentId: wrk_c48a7519c78a46d0b3570f4ecfa84125
modified: 1638923283064
created: 1638364944477
fileName: Swagger Petstore 1.0.0
contents: >
  openapi: 3.0.0


  info:
    version: 0.1.0
    title: Cliente Experience APIs
    description: API da camada Experience responsável por enviar dos dados do cliente
    x-kubernetes-ingress-metadata:
      name: "cliente-e-api"
  tags:
    - name: Cliente
      description: "Interface Experience de clientes"

  servers:
    - url: /
      x-kubernetes-backend:
        servicePort: 4003
        serviceName: "cliente-e-api"

  # adiciona rate limiting


  # x-kong-plugin-rate-limiting:


  #   name: rate-limiting


  #   enabled: true


  #   service: 'cliente-e-api'


  #   config:


  #     minute: 5


  #     policy: local


  # key-auth requires to add credentials to Kong, which is not supported through OpenAPI specs.


  # adiciona key auth


  # Para acessar o serviço, enviar o header "apiKey" com uma credencial válida


  # x-kong-plugin-key-auth:


  #   name: key-auth


  #   config:


  #     key_names:


  #       -  apiKey


  #     key_in_query: false


  paths:
    /cliente/{cpf}:
      get:
        tags:
          - Cliente
        description: "Retorna o cliente com o cpf informado"
        operationId: retornaClientePorId
        parameters:
          - in: path
            name: cpf
            description: "Cpf do usuário a ser buscado. Precisa obedecer a regex: [0-9]{11}"
            schema:
              pattern: "[0-9]{11}"
              type: string
            required: true
        responses:
          "200":
            description: "Retorna o cliente com o cpf informado"
            content:
              application/json:
                schema:
                  oneOf:
                    - $ref: "#/components/schemas/Cliente"
                    - $ref: "#/components/schemas/ErrorModel"
                examples:
                  Success:
                    $ref: "#/components/examples/Cliente"
                  Not Found:
                    value:
                      error: "Cliente não encontrado"
                      from: "VTG-cliente-E-api"
          "400":
            description: "CPF inválido"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorModel"
                examples:
                  response:
                    value:
                      error: "CPF inválido"
                      from: "VTG-cliente-E-api"
          "500":
            description: "Erro inesperado"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorModel"
                examples:
                  response:
                    value:
                      error: "Erro inesperado no servidor"
                      from: "VTG-cliente-E-api"
    /cliente/{cpf}/algumacoisa:
      get:
        tags:
          - Cliente
        description: "Retorna o cliente com o cpf informado"
        operationId: retornaClientePorId1
        parameters:
          - in: path
            name: cpf
            description: "Cpf do usuário a ser buscado. Precisa obedecer a regex: [0-9]{11}"
            schema:
              pattern: "[0-9]{11}"
              type: string
            required: true
        responses:
          "200":
            description: "Retorna o cliente com o cpf informado"
            content:
              application/json:
                schema:
                  oneOf:
                    - $ref: "#/components/schemas/Cliente"
                    - $ref: "#/components/schemas/ErrorModel"
                examples:
                  Success:
                    $ref: "#/components/examples/Cliente"
                  Not Found:
                    value:
                      error: "Cliente não encontrado"
                      from: "VTG-cliente-E-api"
          "400":
            description: "CPF inválido"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorModel"
                examples:
                  response:
                    value:
                      error: "CPF inválido"
                      from: "VTG-cliente-E-api"
          "500":
            description: "Erro inesperado"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorModel"
                examples:
                  response:
                    value:
                      error: "Erro inesperado no servidor"
                      from: "VTG-cliente-E-api"
    /cliente/{cpf}/outracoisa:
      get:
        tags:
          - Cliente
        description: "Retorna o cliente com o cpf informado"
        operationId: retornaClientePorId2
        parameters:
          - in: path
            name: cpf
            description: "Cpf do usuário a ser buscado. Precisa obedecer a regex: [0-9]{11}"
            schema:
              pattern: "[0-9]{11}"
              type: string
            required: true
        responses:
          "200":
            description: "Retorna o cliente com o cpf informado"
            content:
              application/json:
                schema:
                  oneOf:
                    - $ref: "#/components/schemas/Cliente"
                    - $ref: "#/components/schemas/ErrorModel"
                examples:
                  Success:
                    $ref: "#/components/examples/Cliente"
                  Not Found:
                    value:
                      error: "Cliente não encontrado"
                      from: "VTG-cliente-E-api"
          "400":
            description: "CPF inválido"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorModel"
                examples:
                  response:
                    value:
                      error: "CPF inválido"
                      from: "VTG-cliente-E-api"
          "500":
            description: "Erro inesperado"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorModel"
                examples:
                  response:
                    value:
                      error: "Erro inesperado no servidor"
                      from: "VTG-cliente-E-api"

    /cliente/{cpf}/outracoisadois:
      get:
        tags:
          - Cliente
        description: "Retorna o cliente com o cpf informado"
        operationId: retornaClientePorId3
        parameters:
          - in: path
            name: cpf
            description: "Cpf do usuário a ser buscado. Precisa obedecer a regex: [0-9]{11}"
            schema:
              pattern: "[0-9]{11}"
              type: string
            required: true
        responses:
          "200":
            description: "Retorna o cliente com o cpf informado"
            content:
              application/json:
                schema:
                  oneOf:
                    - $ref: "#/components/schemas/Cliente"
                    - $ref: "#/components/schemas/ErrorModel"
                examples:
                  Success:
                    $ref: "#/components/examples/Cliente"
                  Not Found:
                    value:
                      error: "Cliente não encontrado"
                      from: "VTG-cliente-E-api"
          "400":
            description: "CPF inválido"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorModel"
                examples:
                  response:
                    value:
                      error: "CPF inválido"
                      from: "VTG-cliente-E-api"
          "500":
            description: "Erro inesperado"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorModel"
                examples:
                  response:
                    value:
                      error: "Erro inesperado no servidor"
                      from: "VTG-cliente-E-api"
    /cliente:
      post:
        x-kong-plugin-key-auth:
          name: key-auth
          config:
            key_names:
              - apiKey
            key_in_query: false

        tags:
          - Cliente
        description: "Cadastra o cliente no sistema"
        operationId: cadastraCliente
        requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cliente"

        responses:
          "201":
            description: "Retorna o cliente com o cpf informado"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ResponseCliente"
          "400":
            description: "Erro de validação do cliente"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorModel"
                examples:
                  response:
                    value:
                      error: '{"cpf":"must match ''[0-9]{11}''"}'
                      from: "VTG-cliente-E-api"
          "500":
            description: "Erro inesperado"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorModel"
                examples:
                  response:
                    value:
                      error: "Erro inesperado no servidor"
                      from: "VTG-cliente-E-api"
          "502":
            description: "Erro de integração"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorModel"
                examples:
                  response:
                    value:
                      error: "Falha ao chamar a API <nome-da-api>"
                      from: "VTG-cliente-E-api"

  components:
    schemas:
      ErrorModel:
        type: object
        properties:
          error:
            type: string
          from:
            type: string

      Cliente:
        type: object
        required:
          - nome
          - cpf
          - idade
          - data_de_nascimento
          - sexo
          - primeira_compra
          - cep
          - endereco_1
          - endereco_2
          - bairro
          - cidade
          - estado
          - email
        properties:
          nome:
            type: string
            maxLength: 100
          cpf:
            type: string
            maxLength: 11
          idade:
            type: integer
            minimum: 1
            maximum: 999
          data_de_nascimento:
            type: string
            format: date
          sexo:
            type: string
            enum:
              - "F"
              - "M"
          primeira_compra:
            type: boolean
            default: false
          cep:
            type: string
            maxLength: 8
          endereco_1:
            type: string
            maxLength: 150
          endereco_2:
            type: string
            maxLength: 150
          bairro:
            type: string
            maxLength: 50
          cidade:
            type: string
            maxLength: 50
          estado:
            type: string
            enum:
              - "AC"
              - "AL"
              - "AM"
              - "AP"
              - "BA"
              - "CE"
              - "DF"
              - "ES"
              - "GO"
              - "MA"
              - "MG"
              - "MS"
              - "MT"
              - "PA"
              - "PB"
              - "PE"
              - "PI"
              - "PR"
              - "RJ"
              - "RN"
              - "RO"
              - "RR"
              - "RS"
              - "SC"
              - "SE"
              - "SP"
              - "TO"
          email:
            type: string
            maxLength: 100

        example:
          nome: "Abel Silva"
          cpf: "50534475787"
          idade: 22
          data_de_nascimento: "1995-11-09"
          sexo: "M"
          primeira_compra: false
          cep: "22000212"
          endereco_1: "R. Volta Grande"
          endereco_2: ""
          bairro: "Tijuca"
          cidade: "Rio de Janeiro"
          estado: "RJ"
          email: "asilva@vertigo.com.br"

      ResponseCliente:
        type: object
        required:
          - id
          - nome
          - cpf
          - idade
          - data_de_nascimento
          - sexo
          - primeira_compra
          - cep
          - endereco_1
          - endereco_2
          - bairro
          - cidade
          - estado
          - email
        properties:
          id:
            type: integer
          nome:
            type: string
            maxLength: 100
          cpf:
            type: string
            maxLength: 11
          idade:
            type: integer
            minimum: 1
            maximum: 999
          data_de_nascimento:
            type: string
            format: date
          sexo:
            type: string
            enum:
              - "F"
              - "M"
          primeira_compra:
            type: boolean
            default: false
          cep:
            type: string
            maxLength: 8
          endereco_1:
            type: string
            maxLength: 150
          endereco_2:
            type: string
            maxLength: 150
          bairro:
            type: string
            maxLength: 50
          cidade:
            type: string
            maxLength: 50
          estado:
            type: string
            enum:
              - "AC"
              - "AL"
              - "AM"
              - "AP"
              - "BA"
              - "CE"
              - "DF"
              - "ES"
              - "GO"
              - "MA"
              - "MG"
              - "MS"
              - "MT"
              - "PA"
              - "PB"
              - "PE"
              - "PI"
              - "PR"
              - "RJ"
              - "RN"
              - "RO"
              - "RR"
              - "RS"
              - "SC"
              - "SE"
              - "SP"
              - "TO"
          email:
            type: string
            maxLength: 100

        example:
          id: 199
          nome: "Silva Abel"
          cpf: "12345678900"
          idade: 22
          data_de_nascimento: "1995-11-09"
          sexo: "M"
          primeira_compra: true
          cep: "22000212"
          endereco_1: "R. Volta Grande"
          endereco_2: ""
          bairro: "Tijuca"
          cidade: "Rio de Janeiro"
          estado: "RJ"
          email: "sabel@vertigo.com.br"

    examples:
      Cliente:
        value:
          nome: "Silva Abel"
          cpf: "12345678900"
          idade: 22
          data_de_nascimento: "11/09/1995"
          sexo: "M"
          primeira_compra: true
          cep: "22000212"
          endereco_1: "R. Volta Grande"
          endereco_2: ""
          bairro: "Tijuca"
          cidade: "Rio de Janeiro"
          estado: "RJ"
          email: "sabel@vertigo.com.br"
contentType: yaml
